#!/usr/bin/env python3
"""Prepare a local Codex curation prompt without calling any model provider."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from discover_ai_sources import DEFAULT_CANDIDATES, utc_today

VALID_SCOPES = {
    "skills",
    "prompt-guides",
    "image-guides",
    "model-guides",
    "hermes-agent",
    "all",
}

SCOPE_CATEGORIES = {
    "skills": {"claude_code_skills", "codex_guides", "mcp_tools"},
    "prompt-guides": {"prompt_engineering", "prompt_auditing", "codex_guides"},
    "image-guides": {"image_prompting", "local_image_generation"},
    "model-guides": {"image_prompting", "local_image_generation"},
    "hermes-agent": {"hermes_agent"},
}


def load_candidates(path: Path) -> list[dict[str, Any]]:
    if not path.is_file():
        return []
    payload = json.loads(path.read_text(encoding="utf-8"))
    return [candidate for candidate in payload.get("candidates", []) if isinstance(candidate, dict)]


def select_candidates(candidates: list[dict[str, Any]], scope: str, max_sources: int) -> list[dict[str, Any]]:
    if scope not in VALID_SCOPES:
        raise ValueError(f"Unsupported scope: {scope}")

    filtered = [candidate for candidate in candidates if not candidate.get("blocked")]
    if scope != "all":
        categories = SCOPE_CATEGORIES[scope]
        filtered = [candidate for candidate in filtered if candidate.get("category") in categories]

    filtered = sorted(
        filtered,
        key=lambda item: (-int(item.get("score", 0)), str(item.get("category", "")), str(item.get("id", ""))),
    )
    if max_sources > 0:
        filtered = filtered[:max_sources]
    return filtered


def latest_inbox_report(root: Path) -> str:
    inbox = root / "docs" / "research" / "inbox"
    if not inbox.is_dir():
        return "none"
    reports = sorted(inbox.glob("*.md"))
    if not reports:
        return "none"
    return reports[-1].relative_to(root).as_posix()


def candidate_summary(candidate: dict[str, Any]) -> str:
    tags = ", ".join(candidate.get("tags", [])) or "none"
    return "\n".join(
        [
            f"### {candidate.get('name', 'Unnamed source')}",
            "",
            f"- ID: `{candidate.get('id', 'unknown')}`",
            f"- URL: <{candidate.get('url', '')}>",
            f"- Category: `{candidate.get('category', 'uncategorized')}`",
            f"- Score: `{candidate.get('score', 'unscored')}` ({candidate.get('quality', 'unscored')})",
            f"- Source status: {candidate.get('source_status', 'unverified')}",
            f"- License/source status: {candidate.get('license_hint', 'Unknown')}",
            f"- Tags: {tags}",
            f"- Summary: {candidate.get('summary', 'No summary collected.')}",
            f"- Safety note: {candidate.get('safety_note', 'Review before use.')}",
            "",
        ]
    )


def render_local_prompt(root: Path, report_date: str, scope: str, dry_run: bool, max_sources: int) -> str:
    candidates = select_candidates(load_candidates(root / DEFAULT_CANDIDATES), scope, max_sources)
    candidate_block = "\n".join(candidate_summary(candidate) for candidate in candidates) or "No candidates selected."
    newest_report = latest_inbox_report(root)
    dry_run_text = "true" if dry_run else "false"

    return f"""# Local Codex Curator Prompt - {report_date}

This file is generated by the no-API-key curator prompt prep workflow. It does
not call Codex, OpenAI APIs, paid LLMs, model providers, or image-generation
models.

## Maintainer Instructions

Run Codex locally using ChatGPT sign-in through Codex CLI or the Codex app. Do
not use an OpenAI API key for GitHub Actions.

```powershell
git switch main
git pull --ff-only origin main
git switch -c codex/curate-research-guides
codex
```

Then paste the prompt below.

After Codex edits locally, run:

```powershell
python scripts/repo_health_check.py
python scripts/safe_autofix.py --check
python -m unittest discover -s tests

git add .
git commit -m "Curate research guide updates"
git push -u origin codex/curate-research-guides
gh pr create --title "Curate research guide updates" --body "Curates public-safe research guide updates from the scout report."
gh pr checks --watch
```

## Ready-To-Copy Prompt

```text
You are helping curate public-safe research guide updates in this repository.

Configuration:

- Scope: {scope}
- Dry run: {dry_run_text}
- Max sources: {max_sources}
- Latest scout report: {newest_report}

Read first:

- AGENTS.md
- docs/publication-policy.md
- docs/research/source-policy.md
- data/research/candidates.json
- docs/research/inbox/*.md

Use only the selected public candidate sources listed below unless the repo
already contains a directly relevant official source link.

Required behavior:

- Keep the diff focused and reviewable.
- Do not use OpenAI API keys, model-provider API keys, paid LLM calls, or cloud
  Codex GitHub Actions.
- If dry_run is true, propose edits and files to change, but do not edit files.
- If dry_run is false, edit only relevant Markdown guide files and tests/docs
  that are directly needed.
- Do not create releases, publish packages, run image-generation models, or
  push directly to main.
- Do not copy leaked prompts, private data, prompt dumps, copyrighted source
  pages, private paths, private emails, private memories, or private chats.
- Prefer official documentation.
- Label community, unofficial, leak-derived, inferred, or unverified sources.
- Mark unverified install commands as placeholders.
- Include failure modes, verification steps, source links, and license/source
  status in guide updates.
- Keep Hermes Agent coverage limited to Nous Research Hermes Agent as an
  agent/workflow tool. Do not add Hermes language model, model-card, benchmark,
  quantization, GGUF, Ollama, vLLM, SGLang, or local model-running coverage.
- Keep image-generation guidance separated into browser/API, lightweight local,
  advanced local GPU, and cloud workflows.
- On entry-level hardware without a capable GPU, prefer browser/API workflows
  or lightweight local experiments over heavy local diffusion.

Selected sources:

{candidate_block}

Before finishing, run:

- python scripts/repo_health_check.py
- python scripts/safe_autofix.py --check
- python -m unittest discover -s tests

Final response format:

- Summary
- Files changed
- Sources used
- Checks run
- Remaining risks
```
"""


def output_path_for_date(root: Path, report_date: str) -> Path:
    return root / "docs" / "research" / "curated" / f"curator-prompt-{report_date}.md"


def write_prompt(root: Path, report_date: str, scope: str, dry_run: bool, max_sources: int) -> Path:
    path = output_path_for_date(root, report_date)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_local_prompt(root, report_date, scope, dry_run, max_sources), encoding="utf-8")
    return path


def write_issue_body(path: Path, report_date: str, scope: str, dry_run: bool, max_sources: int, issue_body: Path) -> None:
    body = "\n".join(
        [
            "Run this locally in Codex when you have usage.",
            "",
            f"- Date: {report_date}",
            f"- Scope: {scope}",
            f"- Dry run: {str(dry_run).lower()}",
            f"- Max sources: {max_sources}",
            f"- Prompt file: `{path.as_posix()}`",
            "",
            "This workflow prepared a prompt only. It did not call Codex, use an OpenAI API key, call a paid LLM, or create AI-written guide content.",
            "",
        ]
    )
    issue_body.parent.mkdir(parents=True, exist_ok=True)
    issue_body.write_text(body, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a local Codex curation prompt.")
    parser.add_argument("--root", default=Path("."), type=Path)
    parser.add_argument("--date", default=utc_today())
    parser.add_argument("--scope", default="all", choices=sorted(VALID_SCOPES))
    parser.add_argument("--dry-run", default="true", choices=["true", "false"])
    parser.add_argument("--max-sources", default=5, type=int)
    parser.add_argument("--issue-body", default=None, type=Path)
    args = parser.parse_args(argv)

    root = args.root.resolve()
    dry_run = args.dry_run == "true"
    path = write_prompt(root, args.date, args.scope, dry_run, args.max_sources)
    print(f"Wrote {path.relative_to(root)}")
    if args.issue_body:
        write_issue_body(path.relative_to(root), args.date, args.scope, dry_run, args.max_sources, args.issue_body)
        print(f"Wrote {args.issue_body}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
