#!/usr/bin/env python3
"""Generate a daily public-safe research inbox report."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from discover_ai_sources import DEFAULT_CANDIDATES, has_secret_looking_text, redact_secret_text, utc_today


def report_path_for_date(root: Path, report_date: str) -> Path:
    return root / "docs" / "research" / "inbox" / f"{report_date}.md"


def candidate_line(candidate: dict[str, Any]) -> str:
    score = candidate.get("score", "unscored")
    quality = candidate.get("quality", "unscored")
    name = redact_secret_text(str(candidate.get("name", "Unnamed source")))
    url = redact_secret_text(str(candidate.get("url", "")))
    status = redact_secret_text(str(candidate.get("source_status", "unverified")))
    license_hint = redact_secret_text(str(candidate.get("license_hint", "Unknown")))
    safety_note = redact_secret_text(str(candidate.get("safety_note", "Review before publication.")))
    summary = redact_secret_text(str(candidate.get("summary", "") or "No summary collected."))
    tags = ", ".join(candidate.get("tags", [])) or "none"
    return (
        f"### {name}\n\n"
        f"- URL: <{url}>\n"
        f"- Category: `{candidate.get('category', 'uncategorized')}`\n"
        f"- Score: `{score}` ({quality})\n"
        f"- Source status: {status}\n"
        f"- License/source status: {license_hint}\n"
        f"- Tags: {tags}\n"
        f"- Summary: {summary}\n"
        f"- Safety note: {safety_note}\n"
    )


def render_report(candidates: list[dict[str, Any]], report_date: str, max_candidates: int) -> str:
    usable = [candidate for candidate in candidates if not candidate.get("blocked")]
    blocked = [candidate for candidate in candidates if candidate.get("blocked")]
    usable = sorted(
        usable,
        key=lambda item: (-int(item.get("score", 0)), str(item.get("category", "")), str(item.get("id", ""))),
    )
    if max_candidates > 0:
        usable = usable[:max_candidates]

    lines = [
        f"# Daily AI Skills And Prompt Guide Candidates - {report_date}",
        "",
        "This report is generated by the cheap daily scout. It does not use Codex, OpenAI API keys, paid LLM calls, image-generation models, or release publishing.",
        "",
        "## Scout Rules",
        "",
        "- Collect links, metadata, summaries, source status, license hints, and safety notes only.",
        "- Do not polish or publish guides automatically.",
        "- Do not mirror external repositories, leaked prompt dumps, private content, or full source pages.",
        "- Route curated documentation through curator prompt prep, local Codex, branch, pull request, checks, and human review.",
        "",
        "## Top Candidates For Manual Review",
        "",
    ]

    if usable:
        for candidate in usable:
            lines.append(candidate_line(candidate))
    else:
        lines.append("No usable candidates were collected for this run.\n")

    lines.extend(["", "## Blocked Or Review-Required Sources", ""])
    if blocked:
        for candidate in blocked:
            reasons = "; ".join(candidate.get("block_reasons", [])) or "unspecified"
            lines.append(f"- `{candidate.get('id', 'unknown')}`: {redact_secret_text(reasons)}")
    else:
        lines.append("- None.")

    lines.extend(
        [
            "",
            "## Manual Curator Inputs",
            "",
            "- Run curator prompt prep only with `workflow_dispatch`.",
            "- Start the local Codex prompt with `dry_run=true` and a small `max_sources` value.",
            "- Verify installation commands against official documentation before publishing.",
            "- Keep Hermes Agent coverage limited to Nous Research Hermes Agent workflows, not Hermes language models.",
            "- Keep image-generation guidance separated into browser/API, lightweight local, advanced local GPU, and cloud workflows.",
            "",
            "## Source Policy Reminders",
            "",
            "- Prefer official documentation when available.",
            "- Label unofficial, community, leaked, inferred, or unverified sources.",
            "- Do not republish leaked system prompts verbatim.",
            "- Respect licenses and avoid abuse, credential theft, exfiltration, malware, bypass, or jailbreak guidance.",
            "- Do not publish secrets, tokens, private paths, private conversations, private memories, or private user data.",
            "",
        ]
    )
    report = "\n".join(lines)
    if has_secret_looking_text(report):
        report = redact_secret_text(report)
    return report


def render_issue_body(report_path: Path, report_date: str, candidates: list[dict[str, Any]]) -> str:
    usable_count = sum(1 for candidate in candidates if not candidate.get("blocked"))
    blocked_count = sum(1 for candidate in candidates if candidate.get("blocked"))
    return "\n".join(
        [
            "Daily AI skills and prompt guide candidates",
            "",
            f"- Date: {report_date}",
            f"- Report: `{report_path.as_posix()}`",
            f"- Usable candidates: {usable_count}",
            f"- Blocked or review-required candidates: {blocked_count}",
            "",
            "This issue is an inbox pointer only. It does not publish curated guides and does not run Codex.",
            "",
        ]
    )


def load_candidates(path: Path) -> list[dict[str, Any]]:
    if not path.is_file():
        return []
    payload = json.loads(path.read_text(encoding="utf-8"))
    return [candidate for candidate in payload.get("candidates", []) if isinstance(candidate, dict)]


def write_report(root: Path, report_date: str, candidates: list[dict[str, Any]], max_candidates: int) -> Path:
    path = report_path_for_date(root, report_date)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_report(candidates, report_date, max_candidates), encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a daily research report.")
    parser.add_argument("--root", default=Path("."), type=Path)
    parser.add_argument("--candidates", default=DEFAULT_CANDIDATES, type=Path)
    parser.add_argument("--date", default=utc_today())
    parser.add_argument("--max-candidates", default=20, type=int)
    parser.add_argument("--issue-body", default=None, type=Path)
    args = parser.parse_args(argv)

    root = args.root.resolve()
    candidates = load_candidates(args.candidates)
    report_path = write_report(root, args.date, candidates, args.max_candidates)
    print(f"Wrote {report_path.relative_to(root)}")

    if args.issue_body:
        args.issue_body.parent.mkdir(parents=True, exist_ok=True)
        body = render_issue_body(report_path.relative_to(root), args.date, candidates)
        args.issue_body.write_text(body, encoding="utf-8")
        print(f"Wrote {args.issue_body}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
